### ISSUE TITLE
Vuejs Demo App

### ISSUE THREAD

**Issue by ydennisy** [aragon/dao-kits#22]
Hello,
Do you plan to create a template which can be started via the Aragon CLI to create Vuejs boilerplate application?

**Comment by izqui** [comment]
We don't right now, but that would be a great contribution!

You can fork [aragon-react-boilerplate](https://github.com/aragon/aragon-react-boilerplate) and base it on Vue rather than React. Our UI toolkit, [aragon-ui](https://github.com/aragon/aragon-ui), is also React so it may need some custom UI work to make it feel like an Aragon app.

Closing the issue here, as it is not related to DAO kits, but feel free to re-open under the [aragon-cli](https://github.com/aragon/aragon-cli) repo if you end up working on it, we'd happily link it as an option for starting a project.
